### ISSUE TITLE
scoop install nmap - Access denied, can't find ncat (nmap still works though)

### ISSUE THREAD

**Issue by 7anner** [lukesampson/scoop#1495]
```
7anner $ scoop install nmap
Installing 'nmap' (7.31).
Loading nmap-7.31-setup.exe from cache
Checking hash of nmap-7.31-setup.exe... ok.
Running installer... System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.set_EnableRaisingEvents(Boolean value)
   at Microsoft.PowerShell.Commands.StartProcessCommand.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
rm : Cannot remove item C:\Users\7anner\scoop\apps\nmap\7.31\nmap-7.31-setup.exe: Access to the path
'C:\Users\7anner\scoop\apps\nmap\7.31\nmap-7.31-setup.exe' is denied.
At C:\Users\7anner\scoop\apps\scoop\current\lib\install.ps1:627 char:13
+             rm $prog
+             ~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Users\7anner...-7.31-setup.exe:FileInfo) [Remove-Item], Unaut
   horizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemComm
   and
Installer added '~\scoop\apps\nmap\7.31' to path. Removing.
Linking ~\scoop\apps\nmap\current => ~\scoop\apps\nmap\7.31
Creating shim for 'nmap'.
Creating shim for 'ncat'.
Can't shim 'ncat.exe': File doesn't exist.
7anner $ nmap --version

Nmap version 7.31 ( https://nmap.org )
Platform: i686-pc-windows-windows
Compiled with: nmap-liblua-5.3.3 openssl-1.0.2j nmap-libpcre-7.6 Npcap-0.10 r9 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: iocp poll select
7anner $ ncat --version
ncat : The term 'ncat' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ncat --version
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (ncat:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

7anner $
```
For what it's worth, I opened up the cached installer in 7zip and ncat sure looks like it's in there.

**Comment by r15ch13** [comment]
`Access to the path 'C:\Users\7anner\scoop\apps\nmap\7.31\nmap-7.31-setup.exe' is denied.`
Hm, AntiVirus maybe or no permissions?

**Comment by 7anner** [comment]
Perhaps the installer is still in use / ncat hasn't yet been copied?
```
Windows PowerShell
Copyright (C) 2012 Microsoft Corporation. All rights reserved.

~ $ scoop uninstall nmap
Uninstalling 'nmap' (7.31).
Unlinking ~\scoop\apps\nmap\current
Removing older version (7.31).
Couldn't remove '~\scoop\apps\nmap\7.31'; it may be in use.
'nmap' was uninstalled.
~ $ scoop uninstall nmap
Uninstalling 'nmap' ().
'nmap' was uninstalled.
~ $ scoop uninstall nmap
'nmap' isn't installed.
~ $ scoop install nmap
Installing 'nmap' (7.31).
Loading nmap-7.31-setup.exe from cache
Checking hash of nmap-7.31-setup.exe... ok.
Running installer... System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.set_EnableRaisingEvents(Boolean value)
   at Microsoft.PowerShell.Commands.StartProcessCommand.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
rm : Cannot remove item C:\Users\tfiala\scoop\apps\nmap\7.31\nmap-7.31-setup.exe: The process cannot access the
file 'C:\Users\tfiala\scoop\apps\nmap\7.31\nmap-7.31-setup.exe' because it is being used by another process.
At C:\Users\tfiala\scoop\apps\scoop\current\lib\install.ps1:627 char:13
+             rm $prog
+             ~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\tfiala...-7.31-setup.exe:FileInfo) [Remove-Item], IOExcepti
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
Installer added '~\scoop\apps\nmap\7.31' to path. Removing.
Linking ~\scoop\apps\nmap\current => ~\scoop\apps\nmap\7.31
Creating shim for 'nmap'.
Creating shim for 'ncat'.
Can't shim 'ncat.exe': File doesn't exist.
~ $ rm C:\Users\tfiala\scoop\apps\nmap\7.31\nmap-7.31-setup.exe
~ $ Test-Path C:\Users\tfiala\scoop\apps\nmap\7.31\nmap-7.31-setup.exe -PathType Leaf
False
~ $ Test-Path C:\Users\tfiala\scoop\apps\nmap\7.31\ncat.exe -PathType Leaf
True
~ $
```

**Comment by r15ch13** [comment]
Do you get the UAC question from Windows? Did you try `scoop update` (because in the current version, `install.ps1:627` doesn't run `rm` :smile:)

**Comment by rasa** [comment]
It appears this issue has been resolved. If not, please reopen, or let us know. Thanks!
