### ISSUE TITLE
Sourcetree crashes on startup if installed on a machine where Git was installed with scoop

### ISSUE THREAD

**Issue by grootknol** [lukesampson/scoop#1828]
This has bugged me for three this. I'm on a new machine where I decided to install as much of my tools as possible using scoop. First installation was git, of course. Sourcetree was one of the last. Both with scoop. Everytime Sourcetree started I got a crash with an option to submit my logs to Atlassian. 

Initially I blamed the Sourcetree installation from scoop. Uninstalled and reinstalled with Atlassian installer and got the same behavior. I had an old installer from a few months ago in my old machine, but when I tried it got the same crash.

There was no clue in the Windows Event Viewer application logs, so I looked for a Sourcetree log. There I found some messages about Git tools returning status -1. 

The tools were installed (with scoop) and I couldn't believe there was some problem, but I decided to try removing Git (`scoop uninstall git`) and reinstalling Sourcetree once more. I installed Sourcetree first, with scoop, expecting to get the option to install the PortableGit from Sourcetree and break any dependencies from it with scoop's Git. This time scoop's Sourcetree didn't even start, so I uninstalled it.

When I installed Sourcetree with Atlassian installer, with no previous installation of Git in the system, Sourcetree started without issues, using its own PortableGit. I then reinstalled git using scoop and Sourcetree continued to work.

I can't understand whats the issue with Sourcetree but it seems scoop installed Git is messing with it if installed first.

**Comment by matthewjberger** [comment]
Does it still fail if you run `scoop reset git` after the SourceTree installation?

**Comment by clowtown** [comment]
I don't know if this is the same problem, but at the risk of not creating another issue: Scoop install of GIT (and many other things), installed SourceTree and tried various fix/reset as well as Atlassian documentation on removing Windows AppData user.config files that may have been corrupted.

`Application: sourcetree.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
   at Squirrel.UpdateManager.getUpdateExe()
   at Squirrel.UpdateManager.getApplicationName()
   at Squirrel.UpdateManager..ctor(System.String, System.String, System.String, Squirrel.IFileDownloader)
   at SourceTree.App.EnsureSquirrelExecutionStubIsCopied()
   at SourceTree.App..ctor()
   at SourceTree.App.Main()`

Windows AppEvent log 
Faulting application path: C:\Users\..\scoop\apps\sourcetree\current\lib\net45\sourcetree.exe
Faulting module path: C:\windows\System32\KERNELBASE.dll
