### ISSUE TITLE
Elasticsearch post-install script error

### ISSUE THREAD

**Issue by neeasade** [lukesampson/scoop#2172]
on install:

```
Running post-install script...
gc : Cannot find path 'C:\Users\ISOM\scoop\apps\elasticsearch\6.2.3\bin\elasticsearch.in.bat' because it does not
exist.
At line:3 char:6
+     (gc "$original_dir\bin\elasticsearch.in.bat") | % { $_ -replace ' ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\ISOM\s...icsearch.in.bat:String) [Get-Content], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

'elasticsearch' (6.2.3) was installed successfully!
```

and then when I try to run:

```
elasticsearch
[2018-04-02T17:33:07,474][INFO ][o.e.n.Node               ] [] initializing ...
[2018-04-02T17:33:07,546][INFO ][o.e.e.NodeEnvironment    ] [kVv83aW] using [1] data paths, mounts [[OSDisk (C:)]], net usable_space [388.7gb], net total_space [476.4gb], types [NTFS]
[2018-04-02T17:33:07,546][INFO ][o.e.e.NodeEnvironment    ] [kVv83aW] heap size [989.8mb], compressed ordinary object pointers [true]
[2018-04-02T17:33:07,550][INFO ][o.e.n.Node               ] node name [kVv83aW] derived from node ID [kVv83aWeT32jouS3Zxd2iw]; set [node.name] to override
[2018-04-02T17:33:07,550][INFO ][o.e.n.Node               ] version[6.2.3], pid[4316], build[c59ff00/2018-03-13T10:06:29.741383Z], OS[Windows 10/10.0/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_141/25.141-b15]
[2018-04-02T17:33:07,550][INFO ][o.e.n.Node               ] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=C:\Users\ISOM\AppData\Local\Temp\elasticsearch, -XX:+HeapDumpOnOutOfMemoryError, -XX:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, -XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Delasticsearch, -Des.path.home=C:\Users\ISOM\scoop\apps\elasticsearch\current, -Des.path.conf=C:\Users\ISOM\scoop\apps\elasticsearch\current\config]
[2018-04-02T17:33:07,604][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin aggs-matrix-stats due to jar hell
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.2.3.jar:6.2.3]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.2.3.jar:6.2.3]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.2.3.jar:6.2.3]
Caused by: java.lang.IllegalStateException: failed to load plugin aggs-matrix-stats due to jar hell
        at org.elasticsearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:475) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:420) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:146) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.node.Node.<init>(Node.java:303) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.3.jar:6.2.3]
        ... 6 more
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "C:\Users\ISOM\scoop\apps\elasticsearch\6.2.3\modules\aggs-matrix-stats\aggs-matrix-stats-6.2.3.jar" "read")
        at java.security.AccessControlContext.checkPermission(Unknown Source) ~[?:1.8.0_141]
        at java.security.AccessController.checkPermission(Unknown Source) ~[?:1.8.0_141]
        at java.lang.SecurityManager.checkPermission(Unknown Source) ~[?:1.8.0_141]
        at java.lang.SecurityManager.checkRead(Unknown Source) ~[?:1.8.0_141]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_141]
        at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_141]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_141]
        at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_141]
        at org.elasticsearch.bootstrap.JarHell.checkJarHell(JarHell.java:180) ~[elasticsearch-core-6.2.3.jar:6.2.3]
        at org.elasticsearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:460) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:420) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:146) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.node.Node.<init>(Node.java:303) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.node.Node.<init>(Node.java:246) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:323) ~[elasticsearch-6.2.3.jar:6.2.3]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.2.3.jar:6.2.3]
        ... 6 more
```

**Comment by AJua** [comment]
@neeasade 
The issue should be fixed in the extras bucket.
Please update and reinstall Elasticsearch.

**Comment by neeasade** [comment]
Filed on the wrong repo, oops. Thanks!
