### ISSUE TITLE
MongoDB: Failed to extract files

### ISSUE THREAD

**Issue by ClintH** [lukesampson/scoop#2188]
Having issues installing MongoDB on Win10 x64:

```
Extracting... DEBUG:  355+              >>>> $null = mkdir "$dir\_tmp"
DEBUG:  422+     'mkdir' =  >>>> { new-item -type directory @args }
DEBUG:     ! CALL function '<ScriptBlock>'  (defined in file
'C:\Users\ch\scoop\apps\scoop\current\lib\core.ps1')
DEBUG:  422+     'mkdir' = {  >>>> new-item -type directory @args }
DEBUG:  422+     'mkdir' = { new-item -type directory @args  >>>> }
DEBUG:  356+              >>>> & $extract_fn "$dir\$fname" "$dir\_tmp"
DEBUG:  578+ function extract_msi($path, $to)  >>>> {
DEBUG:     ! CALL function 'extract_msi'  (defined in file
'C:\Users\ch\scoop\apps\scoop\current\lib\install.ps1')
DEBUG:  579+      >>>> $logfile = "$(split-path $path)\msi.log"
DEBUG:  579+     $logfile = "$( >>>> split-path $path)\msi.log"
DEBUG:     ! SET $logfile = 'C:\Users\ch\scoop\apps\mongodb\3.6.3\msi.log'.
DEBUG:  580+      >>>> $ok = run 'msiexec' @('/a', "`"$path`"", '/qn',
"TARGETDIR=`"$to`"", "/lwe `"$logfile`"")
DEBUG:  489+ function run($exe, $arg, $msg, $continue_exit_codes)  >>>> {
DEBUG:     ! CALL function 'run'  (defined in file
'C:\Users\ch\scoop\apps\scoop\current\lib\install.ps1')
DEBUG:  490+     if( >>>> $msg) { write-host "$msg " -nonewline }
DEBUG:  493+          >>>> $parameters = @{ }
DEBUG:     ! SET $parameters = 'System.Collections.Hashtable'.
DEBUG:  494+         if ( >>>> $arg)
DEBUG:  496+              >>>> $parameters.arg = $arg;
DEBUG:  499+          >>>> $proc = start-process $exe -wait -ea stop -passthru
@parameters
DEBUG:  510+          >>>> write-host -f darkred $_.exception.tostring()
System.Management.Automation.RuntimeException: Cannot convert value to type System.String. ---> System.Management.Automation.PSInvalidCastException: Cannot convert value to type System.String. ---> System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ProcessName()
   at System.Diagnostics.Process.ToString()
   at System.Management.Automation.PSObject.ToString(ExecutionContext context, Object obj, String separator, String format, IFormatProvider formatProvider, Boolean recurse, Boolean unravelEnumeratorOnRecurse)
   --- End of inner exception stack trace ---
   at System.Management.Automation.PSObject.ToStringParser(ExecutionContext context, Object obj)
   at System.Management.Automation.ScriptDebugger.TraceVariableSet(String varName, Object value)
   at System.Management.Automation.VariableOps.SetVariableValue(VariablePath variablePath, Object value, ExecutionContext executionContext, AttributeBaseAst[] attributeAsts)
   at System.Management.Automation.Interpreter.FuncCallInstruction`5.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
DEBUG:  511+         return  >>>> $false
DEBUG:  515+  >>>> }
DEBUG:     ! SET $ok = 'False'.
DEBUG:  581+     if( >>>> !$ok) { abort "Failed to extract files from
$path.`nLog file:`n  $(friendly_path $logfile)" }
DEBUG:  581+     if(!$ok) {  >>>> abort "Failed to extract files from
$path.`nLog file:`n  $(friendly_path $logfile)" }
DEBUG:  581+     if(!$ok) { abort "Failed to extract files from $path.`nLog
file:`n  $( >>>> friendly_path $logfile)" }
DEBUG:  150+ function friendly_path($path)  >>>> {
DEBUG:     ! CALL function 'friendly_path'  (defined in file
'C:\Users\ch\scoop\apps\scoop\current\lib\core.ps1')
DEBUG:  151+      >>>> $h = (Get-PsProvider 'FileSystem').home;
if(!$h.endswith('\')) { $h += '\' }
DEBUG:     ! SET $h = 'C:\Users\ch'.
DEBUG:  151+     $h = (Get-PsProvider 'FileSystem').home; if( >>>>
!$h.endswith('\')) { $h += '\' }
DEBUG:  151+     $h = (Get-PsProvider 'FileSystem').home; if(!$h.endswith('\'))
 {  >>>> $h += '\' }
DEBUG:     ! SET $h = 'C:\Users\ch\'.
DEBUG:  152+     if( >>>> $h -eq '\') { return $path }
DEBUG:  153+     return  >>>> "$path" -replace ([regex]::escape($h)), "~\"
DEBUG:  154+  >>>> }
DEBUG:   48+ function abort($msg, [int] $exit_code=1)  >>>> { write-host $msg
-f red; exit $exit_code }
DEBUG:     ! CALL function 'abort'  (defined in file
'C:\Users\ch\scoop\apps\scoop\current\lib\core.ps1')
DEBUG:   48+ function abort($msg, [int] $exit_code=1) {  >>>> write-host $msg
-f red; exit $exit_code }
Failed to extract files from C:\Users\ch\scoop\apps\mongodb\3.6.3\mongodb-win32-x86_64-2008plus-ssl-3.6.3-signed.msi.
Log file:
  ~\scoop\apps\mongodb\3.6.3\msi.log
DEBUG:   48+ function abort($msg, [int] $exit_code=1) { write-host $msg -f red;
  >>>> exit $exit_code }
DEBUG:     ! SET $foreach = ''.
DEBUG:   37+  >>>> }
```

**Comment by rasa** [comment]
This issue belongs in the [Main](https://github.com/ScoopInstaller/Main) bucket. Unfortunately, we cannot move this issue on this end, so it is being closed.
If this is still an issue, please create a new issue in the Main bucket via https://github.com/ScoopInstaller/Main/issues/new?body=Moved+from+https%3A%2F%2Fgithub.com%2Flukesampson%2Fscoop%2Fissues%2F2188
