### ISSUE TITLE
msi error 2203 while updating 7zip

### ISSUE THREAD

**Issue by guillermooo** [lukesampson/scoop#460]
```
=== Logging started: 17.08.2015  10:12:49 ===
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2203. The arguments are: C:\Users\xxx\appdata\local\scoop\apps\7zip\9.38\_scoop_extract\7z938-x64.msi, -2147287008, 
=== Logging stopped: 17.08.2015  10:12:50 ===
```

Maybe related:

http://stackoverflow.com/questions/21846381/error-2203-while-extracting-msi

**Comment by deevus** [comment]
What's your OS?

**Comment by guillermooo** [comment]
Win 7 Pro 64bit

**Comment by lukesampson** [comment]
Is there a log file at `C:\Users\[username]\appdata\local\scoop\apps\7zip\9.38\_scoop_extract\7z938-x64.log`? That might have some more info.

**Comment by guillermooo** [comment]
There's no file in that location. Apparently I'm using a system-wide install of 7zip, probably because I never was able to install 7zip via scoop.

**Comment by guillermooo** [comment]
```
installing 7zip (9.38)
loading http://www.7-zip.org/a/7z938-x64.msi from cache...
checking hash...ok
extracting...exit code was 1603
failed to extract files from C:\Users\xxx\appdata\local\scoop\apps\7zip\9.38\7z938-x64.msi. log file: ~\appdata\local\scoop\apps\7zip\9.38\msi.log
```

**Comment by lukesampson** [comment]
Strange. Is there nothing in ~\appdata\local\scoop\apps\7zip\9.38\ at all?
Can you try running the msi with the /a switch and /l to specify your own
log file?

**Comment by guillermooo** [comment]
Fiddling with `msiexec` params I could get it to spit this out:

```
 msiexec.exe /a in\7z920-x64.msi TARGETDIR=C:\Users\XXX\AppData\Local\scoop\out /l C:\Users\XXX\AppData\Local\scoop\my.log
```

```
=== Logging started: 21.08.2015  10:09:17 ===
Action 10:09:17: ADMIN.
Action start 10:09:17: ADMIN.
Action 10:09:17: CostInitialize. Computing space requirements
Action start 10:09:17: CostInitialize.
Action ended 10:09:17: CostInitialize. Return value 1.
Action 10:09:17: FileCost. Computing space requirements
Action start 10:09:17: FileCost.
Action ended 10:09:17: FileCost. Return value 1.
Action 10:09:17: CostFinalize. Computing space requirements
Action start 10:09:17: CostFinalize.
Action ended 10:09:17: CostFinalize. Return value 1.
Action 10:09:17: ExecuteAction.
Action start 10:09:17: ExecuteAction.
Action 10:09:18: ADMIN.
Action start 10:09:18: ADMIN.
Action 10:09:18: CostInitialize. Computing space requirements
Action start 10:09:18: CostInitialize.
Action ended 10:09:18: CostInitialize. Return value 1.
Action 10:09:18: FileCost. Computing space requirements
Action start 10:09:18: FileCost.
Action ended 10:09:18: FileCost. Return value 1.
Action 10:09:18: CostFinalize. Computing space requirements
Action start 10:09:18: CostFinalize.
Action ended 10:09:18: CostFinalize. Return value 1.
Action 10:09:18: InstallValidate. Validating install
Action start 10:09:18: InstallValidate.
Action ended 10:09:19: InstallValidate. Return value 1.
Action 10:09:19: InstallInitialize.
Action start 10:09:19: InstallInitialize.
Action ended 10:09:19: InstallInitialize. Return value 1.
Action 10:09:19: InstallAdminPackage. Copying network install files
Action start 10:09:19: InstallAdminPackage.
Action 10:09:19: GenerateScript. Generating script operations for action:
GenerateScript: Copying network install files
Action ended 10:09:19: InstallAdminPackage. Return value 1.
Action 10:09:19: InstallFiles. Copying new files
Action start 10:09:19: InstallFiles.
InstallFiles: File: Copying new files,  Directory: ,  Size:
Action ended 10:09:19: InstallFiles. Return value 1.
Action 10:09:19: InstallFinalize.
Action start 10:09:19: InstallFinalize.
Action 10:09:19: InstallAdminPackage. Copying network install files
DEBUG: Error 2203:  Database: C:\Users\XXX\AppData\Local\scoop\out\7z920-x64.msi. Cannot op en database file. System error -2147287008
Info 2898.For WixUI_Font_Normal textstyle, the system created a 'Tahoma' font, in 1 character se t, of 13 pixels height.
The installer has encountered an unexpected error installing this package. This may indicate a p roblem with this package. The error code is 2203. The arguments are: C:\Users\XXX\AppData\L ocal\scoop\out\7z920-x64.msi, -2147287008,
MSI (s) (9C:80) [10:09:21:572]: Product: 7-Zip 9.20 (x64 edition) -- The installer has encounter ed an unexpected error installing this package. This may indicate a problem with this package. T he error code is 2203. The arguments are: C:\Users\XXX\AppData\Local\scoop\out\7z920-x64.ms i, -2147287008,

Action ended 10:09:21: InstallFinalize. Return value 3.
Action 10:09:21: Rollback. Rolling back action:
Rollback: Copying network install files
Action ended 10:09:21: ADMIN. Return value 3.
Action ended 10:09:21: ExecuteAction. Return value 3.
Action 10:09:21: FatalError.
Action start 10:09:21: FatalError.
Info 2898.For WixUI_Font_Bigger textstyle, the system created a 'Tahoma' font, in 1 character se t, of 19 pixels height.
DEBUG: Error 2888:  Executing the Binary view failed
The installer has encountered an unexpected error installing this package. This may indicate a p roblem with this package. The error code is 2888. The arguments are: Binary, ,
DEBUG: Error 2826:  Control BottomLine on dialog FatalError extends beyond the boundaries of the  dialog to the right by 5 pixels
The installer has encountered an unexpected error installing this package. This may indicate a p roblem with this package. The error code is 2826. The arguments are: FatalError, BottomLine, to
the right
Action 10:09:21: FatalError. Dialog created
Action ended 10:09:23: FatalError. Return value 2.
Action ended 10:09:23: ADMIN. Return value 3.
=== Logging stopped: 21.08.2015  10:09:23 ===
MSI (c) (08:D0) [10:09:23:315]: Product: 7-Zip 9.20 (x64 edition) -- Installation failed.

MSI (c) (08:D0) [10:09:23:316]: Windows Installer installed the product. Product Name: 7-Zip 9.2 0 (x64 edition). Product Version: 9.20.00.0. Product Language: 1033. Manufacturer: Igor Pavlov.
Installation success or error status: 1603.
```

Note that I'm trying with a lower version than latest intentionally — same result.

The `scoop` source code says that msi installs are deprecated, though. :)

**Comment by lukesampson** [comment]
Only installing MSIs with the old `msi` property in manifests is deprecated—what you did is basically they way scoop extracts files from MSI installers without running the installer.

If you downloaded the MSI manually, maybe it's locked because it was downloaded from the internet. If it's not that, I'm out of ideas sorry.

**Comment by guillermooo** [comment]
It's most definitely a config issue, as on my own PC it works fine. I'll close this out.

**Comment by avishapiro** [comment]
I'm on a work computer and have the same issue. I think it's related to a security setting. Someone on StackOverflow mentioned the problem was fixed by turning off TrendMicro antivirus. I also have this antivirus program running but can't disable it without admin access, which I can't get every time I want to use scoop.

**Comment by lukesampson** [comment]
@avishapiro I'm really sorry but I'm not sure how we can fix this MSI issue. If there was a .zip distribution of 7-zip that would possibly extract without problems, but we're limited to the files hosted on the 7-zip website: .exe and .msi.

You could try asking Igor Pavlov (the 7-zip maintainer) if he'd consider packaging 7-zip as .zip on his [forum](https://sourceforge.net/p/sevenzip/discussion/45797/). I've asked in the past, but I don't think it went anywhere. Maybe if more people request this he'll see the value. This is all assuming that Trend Micro won't detect something in the .zip that it doesn't like.

It's possible that someone already hosts a .zip distribution of 7-zip—if you can find one anywhere I'd be happy to use that instead.

**Comment by avishapiro** [comment]
Thanks @lukesampson. I'm thinking now that my antivirus program isn't the issue. I already had 7zip installed in windows. Additionally, I can manually install the msi file scoop downloads. So it seems like permissions aren't the problem. Can I tell scoop that 7zip is already installed?  I've been able to scoop install other shell programs that don't require 7zip so all is not lost.

**Comment by deevus** [comment]
You could try using lessmsi. I added a configuration option for it because for some reason the inbuilt command was broken.

**Comment by deevus** [comment]
Run `scoop config MSIEXTRACT_USE_LESSMSI $true` and try again

**Comment by avishapiro** [comment]
Thank you @deevus! That worked perfectly (running `scoop config MSIEXTRACT_USE_LESSMSI $true`). I was able to install 7zip, git, openssh and more.

**Comment by nnerik** [comment]
Thanks @deevus!

**Comment by r15ch13** [comment]
@a59 just `true` or `True`, it will be converted to a Boolean 👍

**Comment by wizofe** [comment]
Love you @deevus.

**Comment by zoof** [comment]
Not sure if there have been changes that make this solution not work any longer.  I installed `lessmsi` and then ran `scoop config MSIEXTRACT_USE_LESSMSI $true`.  But then when I tried to install 7zip, it failed with the following:
```
scoop install 7zip
Installing '7zip' (19.00) [64bit]
Loading 7z1900-x64.msi from cache
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... ERROR Exit code was -1!
Failed to extract files from C:\Users\username\scoop\apps\7zip\19.00\7z1900-x64.msi.
Log file:
  ~\scoop\apps\7zip\19.00\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Main/issues/new?title=7zip%4019.00%3a+decompress+error
```
The contents of the log file are:
```
Extracting 'C:\Users\username\scoop\apps\7zip\19.00\7z1900-x64.msi' to 'C:\Users\username\scoop\apps\7zip\19.00\_tmp\'.
1/102   7zFM.exe
2/102   7-zip32.dll
3/102   7-zip.dll
4/102   7zG.exe
5/102   7z.dll
6/102   7z.exe
7/102   7z.sfx
8/102   7zCon.sfx
9/102   descript.ion
10/102  History.txt
11/102  License.txt
12/102  readme.txt
13/102  7-zip.chm
14/102  en.ttt

Error: System.Exception: Error 'MSPACK_ERR_OPEN' extracting file to \\?\C:\Users\username\scoop\apps\7zip\19.00\_tmp\SourceDir\Files\7-Zip\Lang\en.ttt.
   at LibMSPackN.MSCompressedFile.ExtractTo(String destinationFilename)
   at LessMsi.Msi.Wixtracts.ExtractFiles(Path msi, String outputDir, MsiFile[] filesToExtract, AsyncCallback progressCallback)
   at LessMsi.Cli.Program.DoExtraction(String msiFileName, String outDirName, List`1 filesToExtract)
   at LessMsi.Cli.ExtractCommand.Run(List`1 allArgs)
   at LessMsi.Cli.Program.Main(String[] args)

Usage:
lessmsi <command> [options] <msi_name> [<path_to_extract\>] [file_names]

Commands:
  x  Extracts all or specified files from the specified msi_name.
  l  Lists the contents of the specified msi table as CSV to stdout. Table is
     specified with -t switch. Example: lessmsi l -t Component c:\foo.msi
  v  Lists the value of the ProductVersion Property in the msi
     (typically this is the version of the MSI).
  o  Opens the specified msi_name in the GUI.
  h  Shows this help page.

For more information see http://lessmsi.activescott.com
```
