### ISSUE TITLE
Node NPM Cannot find module 'npmlog'

### ISSUE THREAD

**Issue by rodrigopolo** [lukesampson/scoop#622]
After installing node.js by typing:

```
scoop install nodejs
```

I get the following error when trying to run NPM:

```
module.js:328
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at C:\Users\rpolo\AppData\Local\scoop\apps\nodejs\5.3.0\nodejs\node_modules\npm\bin\npm-cli.js:20:13
    at Object.<anonymous> (C:\Users\rpolo\AppData\Local\scoop\apps\nodejs\5.3.0\nodejs\node_modules\npm\bin\npm-cli.js:76:3)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
```

**Comment by JMBattista** [comment]
Can confirm that I have the same issue. Using the 
```
scoop install nodejs4
```
command works fine but gives v4 instead of v5.

**Comment by damnhandy** [comment]
I had the same issue around the same time, but with the current releases it seems to be resolved. I did some digging and this is more of an NPM issue than a scoop issue. This error is common when NPM can't update itself.

**Comment by felipecrp** [comment]
Got this issue today:

```
=== Logging started: 11/11/2016  23:55:44 ===
Error 1320. The specified path is too long: C:\Users\felipe\AppData\Local\scoop\apps\nodejs\7.1.0\_scoop_extract\nodejs\node_modules\npm\node_modules\npm-registry-client\node_modules\npmlog\node_modules\gauge\node_modules\string-width\node_modules\is-fullwidth-code-point\node_modules\number-is-nan
=== Logging stopped: 11/11/2016  23:56:30 ===
```
